spring:
  datasource:
    druid:
      username: test
      password: test123
      url: jdbc:mysql://127.0.0.1:3306/local?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  profiles:
    active: dev
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 100ms
  cache:
    type: redis
    cache-names: redisCache
  servlet:
    multipart:
      file-size-threshold: 5MB
      max-file-size: 10MB
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  quartz:
    job-store-type: jdbc
    properties:
      org.quartz.scheduler.instanceName: clusteredScheduler
      org.quartz.scheduler.instanceId: AUTO
      org.quartz.scheduler.autoId: true
      org.quartz.jobStore.class: org.quartz.impl.jdbcjobstore.JobStoreTX
      org.quartz.jobStore.isClustered: true
server:
  port: 8082
mybatis:
  type-handlers-package: priv.cxs.springboot2.dao.config
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
