spring:
  datasource:
    druid:
      username: test
      password: test1234
      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  profiles:
    active: dev
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 100ms
  cache:
    type: redis
    cache-names: redisCache
  servlet:
    multipart:
      file-size-threshold: 5MB
      max-file-size: 10MB
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
server:
  port: 8082
mybatis:
  type-handlers-package: priv.cxs.springboot2.dao.config
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
